### ISSUE TITLE
Default encodings for different columns

### ISSUE THREAD

**Issue by padix-key** [molstar/BinaryCIF#7]
Is there some resource (code would also OK for the purpose), that contains the *default* encodings that were used to create the `bcif` files provided by `https://models.rcsb.org/`?

I would like to implement a writer for *bcif*, so it would be helpful to know what reasonable encodings for each PDBx field are.

**Comment by josemduarte** [comment]
I believe the bcif files at models.rcsb.org are written with the Mol* encoder. See this: https://github.com/molstar/molstar/tree/master/src/cli/cif2bcif and this https://github.com/molstar/molstar/tree/master/src/mol-io/common/binary-cif . I'm not familiar with the code but he defaults should be there somewhere.

**Comment by padix-key** [comment]
Thanks for the pointer :+1:
